# Generated by Django 3.2.5 on 2021-07-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.aluno')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso')),
            ],
            options={
                'db_table': 'curso_aluno',
                'managed': True,
                'index_together': {('id_aluno', 'id_curso')},
            },
        ),
    ]
